### ISSUE TITLE
Use DB_REPLICA instead of DB_SLAVE

### ISSUE THREAD

**Issue by justinclloyd** [poke/mediawiki-ListTransclusions#1]
The DB_SLAVE constant, used in SpecialListTransclusions.php, was deprecated in MediaWiki 1.28 and removed in 1.34. It should be updated to DB_REPLICA.

**Comment by poke** [comment]
Fixed in e16b7d1031, and the extension was also updated for MW 1.36 support. – Thanks Justin!
